#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# Some X settings

# Mouse accelleration
xinput --set-prop 12 'libinput Accel Speed' -0.6

# Set wallpaper
# hsetroot -solid '#5e81ac'
hsetroot -solid '#4C566A'

# Start up compositor
picom --experimental-backends --config $HOME/.config/picom/picom.conf &

# Panel
$HOME/.config/polybar/launch.sh

# Start sxkhd
sxhkd &

# Start bspwm
exec bspwm

