#! /bin/sh

# Rationalise once replace monitor
#bspc monitor DisplayPort-3 -d 1 2
bspc monitor -d 1 2 3 4

bspc config border_width 3
bspc config window_gap 8

bspc config focused_border_color "#D8DEE9"
bspc config presel_feedback_color "#D8DEE9"

bspc config normal_border_color "#5E81AC"

bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true
