evaluate-commands %sh{
    files="
        config.kak
        plugins.kak
        mappings.kak
        modeline.kak
    "

    for file in $files; do
        printf "%s\n" "try %{
           source '$HOME/.config/kak/$file'
        } catch %{
            try %{
                echo -debug \"%val{error}\" 
            } catch {
                echo -debug 'Error sourcing $file'
            }
        }"
    done
}
