contexts:
- name: docker-desktop
  color: cyan
  order: 1
- name: docker-for-desktop
  color: cyan
  order: 1
- name: minikube
  color: cyan
  order: 1
- name: dev
  color: green
  order: 10
- name: scratch
  color: green
  order: 20
- name: scratch-private
  color: green
  order: 21
- name: staging
  color: yellow
  order: 30
- name: staging-private
  color: yellow
  order: 31
- name: sandbox
  color: blue
  order: 40
- name: production
  color: red
  order: 50
- name: vault
  color: magenta
  order: 60
history:
  max-items: 20
  max-age: 4w

